#!/usr/bin/env bash

OS='uname -s'

clone_dotfile_repository() {
  git clone git@github.com:rollbrettler/dotfiles.git ~/.dotfiles
}

make_scripts_executable() {
  for script in "decrypt" "encrypt" "mac"; do
    chmod +x ~/.dotfiles/bin/"${script}"
  done
}

link_dotfiles() {
  for dotfile in ".aliases" ".exports" ".secrets" ".wgetrc" ".ssh" ".js"; do
    if [[ -L ~/"${dotfile}" && -d ~/"${dotfile}" ]]; then
      unlink ~/"${dotfile}"
    else
      mv ~/"${dotfile}" ~/.dotfiles/bak/"${dotfile}"
    fi
    ln -s ~/.dotfiles/"${dotfile}" ~/"${dotfile}"
  done
}

install_general_terminal_tools() {
  curl -L http://install.ohmyz.sh | sh
}

if [ "$($OS)" == 'Darwin' ]; then
    echo "Install Mac software"

    # Install xcode tools
    xcode-select --install

    read -p "Please proceed with xcode setup and press the enter key after setup is finished "
    sudo xcrun cc

    clone_dotfile_repository
    make_scripts_executable
    link_dotfiles
    install_general_terminal_tools

    # Execute mac install script
    ~/.dotfiles/bin/mac
else
    echo "Linux #ToDo"
    # clone_dotfile_repository
    # make_scripts_executable
    # install_general_terminal_tools
    # curl https://raw.githubusercontent.com/creationix/nvm/v0.20.0/install.sh | bash

    # Execute mac install script
    # ~/.dotfiles/mac
fi
