#!/usr/bin/env bash

OS='uname -s'

clone_dotfile_repository() {
  git clone git@github.com:rollbrettler/dotfiles.git ~/.dotfiles
}

make_scripts_executable() {
  for script in "decrypt" "encrypt" "mac" "linux"; do
    chmod +x ~/.dotfiles/bin/"${script}"
  done
  chmod +x ~/.dotfiles/install
}

link_dotfiles() {
  for dotfile in ".aliases" ".exports" ".secrets" ".wgetrc" ".ssh" ".js" ".vim" ".zshrc" ".profile"; do
    if [[ -L ~/"${dotfile}" && -d ~/"${dotfile}" ]]; then
      unlink ~/"${dotfile}"
    else
      mv ~/"${dotfile}" ~/.dotfiles/bak/"${dotfile}"
    fi
    ln -s ~/.dotfiles/"${dotfile}" ~/"${dotfile}"
  done
}

link_submodule_files() {
  if [[ -L ~/.dotfiles/.vim/colors/molokai.vim ]]; then
    unlink ~/.dotfiles/.vim/colors/molokai.vim
  else
    mv ~/.dotfiles/.vim/colors/molokai.vim ~/.dotfiles/bak/molokai.vim
  fi
  ln -s ~/.dotfiles/submodules/molokai/colors/molokai.vim ~/.dotfiles/.vim/colors/molokai.vim
}

install_general_terminal_tools() {
  curl -L http://install.ohmyz.sh | sh
}

install_nvm() {
  curl https://raw.githubusercontent.com/creationix/nvm/v0.20.0/install.sh | bash
}

if [ "$($OS)" == 'Darwin' ]; then
    echo "Install Mac software"

    # Install xcode tools
    xcode-select --install

    read -p "Please proceed with xcode setup and press the enter key after setup is finished "
    sudo xcrun cc

    clone_dotfile_repository
    make_scripts_executable
    link_dotfiles
    link_submodule_files
    install_general_terminal_tools

    # Execute mac install script
    ~/.dotfiles/bin/mac
else
    echo "Linux #ToDo"

    sudo apt-get update --assume-yes --quiet
    sudo apt-get install --assume-yes --quiet zsh

    clone_dotfile_repository
    make_scripts_executable
    link_dotfiles
    link_submodule_files
    install_general_terminal_tools
    install_nvm

    # Execute mac install script
    ~/.dotfiles/linux
fi
