#!/usr/bin/env bash

for dotfile in ".aliases" ".gitconfig" ".exports" ".secrets" ".wgetrc" ".ssh" ".js" ".vim" ".zshrc" ".profile" ".atom" ".npmrc" "bin"; do
  if [[ -L ~/"${dotfile}" ]]; then
    unlink ~/"${dotfile}"
  elif [[ -f ~/"${dotfile}" || -d ~/"${dotfile}" ]]; then
    mv ~/"${dotfile}" ~/.dotfiles/bak/"${dotfile}"
  fi
  ln -s ~/.dotfiles/"${dotfile}" ~/"${dotfile}"
done
