#!/usr/bin/env bash

# link_submodule_files() {
#   if [[ -L ~/.dotfiles/.vim/colors/molokai.vim ]]; then
#     unlink ~/.dotfiles/.vim/colors/molokai.vim
#   else
#     mv ~/.dotfiles/.vim/colors/molokai.vim ~/.dotfiles/bak/molokai.vim
#   fi
#
# }

unlink $DOTFILES/.vim/autoload
unlink $DOTFILES/.vim/bundle/vim-hackernews
unlink $DOTFILES/.vim/bundle/nerdtree
unlink $DOTFILES/.vim/colors/molokai.vim

ln -s $DOTFILES/submodules/vim-pathogen/autoload $DOTFILES/.vim/autoload
ln -s $DOTFILES/submodules/vim-hackernews $DOTFILES/.vim/bundle/vim-hackernews
ln -s $DOTFILES/submodules/nerdtree $DOTFILES/.vim/bundle/nerdtree
ln -s $DOTFILES/submodules/molokai/colors/molokai.vim $DOTFILES/.vim/colors/molokai.vim
