#!/usr/bin/env bash

for dotfile in ".aliases" ".gitconfig" ".exports" ".secrets" ".wgetrc" ".ssh" ".js" ".vim" ".zshrc" ".profile" ".atom"; do
  if [[ -L ~/"${dotfile}" && -d ~/"${dotfile}" ]]; then
    unlink ~/"${dotfile}"
  else
    mv ~/"${dotfile}" ~/.dotfiles/bak/"${dotfile}"
  fi
  ln -s ~/.dotfiles/"${dotfile}" ~/"${dotfile}"

  source ~/"${dotfile}"
done
